name: Build and deploy client production

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.11]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install pnpm package manager
        run: corepack enable pnpm && corepack use pnpm@latest
      - name: Install dependencies
        run: pnpm install
      
