name: Build and deploy client production

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Echo the message
              run: |
                  echo "Test CI/CD!"
