name: Build and deploy test client

on:
    push:
        branches:
            - development

env:
    node-version: 20.11

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ env.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node-version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install --no-optional --frozen-lockfile
            - name: Build
              run: pnpm run build
                